package com.example.cw1;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;

public class ArticleInserter {
    public static void main(String[] args) throws IOException {
        String[][] articles = {
                {"Tech Giants Embrace AI for Content Creation","Major tech companies are developing AI tools for writing and design, revolutionizing content creation. This trend raises debates over intellectual property and the future of human creativity. Industry leaders are working on ethical standards to guide responsible AI usage in digital content production."},
                {"The Future of Space Tourism","Space tourism is shifting from sci-fi to reality as private companies launch space flights for civilians. Although prohibitively expensive for most, the sector is expected to grow as costs decrease. Space tourism could reshape our understanding of space, yet regulatory and environmental concerns remain crucial as the industry evolves."},
                {"Cybersecurity Threats in 2024","Cybersecurity is a growing priority as digital threats continue to evolve. With more companies shifting to remote work, vulnerabilities have increased, requiring updated defenses. Hackers exploit weak systems, and companies invest in measures like encryption and multi-factor authentication. Governments are also drafting laws to combat cyber threats effectively."},
                {"Impact of Social Media on Mental Health","Social media is reshaping our social lives, but its impact on mental health is significant. Studies indicate high social media usage correlates with anxiety, depression, and self-esteem issues, particularly among youth. To mitigate these effects, platforms are exploring features that promote positive engagement and reduce harmful content."},
                {"Climate Change and Extreme Weather Events","The frequency of extreme weather events, including hurricanes, floods, and wildfires, has risen due to climate change. Scientists warn that unless emissions are curbed, these events will become more common. Nations are urged to adopt green policies to combat these changes and protect vulnerable communities from climate-related disasters."},
                {"Electric Cars Transform Urban Mobility","Electric cars are becoming more popular, especially in cities. With better charging infrastructure, governments and carmakers are pushing for a shift to electric vehicles. The transition is beneficial for the environment, but challenges like battery disposal and charging accessibility remain to be addressed for a sustainable future."},
                {"5G Technology Revolutionizing Industries","5G technology is being implemented globally, promising faster internet speeds and lower latency. This shift will enable new possibilities in IoT, healthcare, and remote work. However, deploying 5G infrastructure is challenging and costly, and some regions are lagging. Nonetheless, 5G holds transformative potential across industries."},
                {"Advancements in Quantum Computing", "Quantum computing is emerging as a game-changer in data processing. Unlike traditional computers, quantum computers use quantum bits to perform complex calculations faster. The technology is still in its infancy but holds promise for breakthroughs in cryptography, material science, and artificial intelligence."},
                {"The Growing Popularity of Plant-Based Diets","Plant-based diets are gaining traction as more people seek sustainable and ethical eating habits. Many studies link plant-based diets to better health outcomes and reduced environmental impact. While transitioning to such diets can be challenging, the availability of plant-based products is making it easier."},
                {"Cryptocurrency Regulations and Market Impact", "Governments are tightening cryptocurrency regulations in response to market volatility and security concerns. While regulations aim to protect investors, they also pose challenges for market innovation. Some argue that sensible regulations will help cryptocurrency thrive, while others worry they could stifle the decentralized nature of digital currencies."},
                {"E-Commerce Trends in 2024", "The e-commerce sector continues to evolve, with trends such as same-day delivery, personalized shopping experiences, and increased use of artificial intelligence. Retailers are investing in technologies that enhance customer experience. As competition grows, companies are focusing on sustainable practices and social responsibility to attract modern consumers."},
                {"Rise of Electric Scooters in Cities","Electric scooters have become a common sight in cities around the world. They offer an eco-friendly alternative to cars, reducing congestion and emissions. However, safety concerns and regulations vary widely, with some cities struggling to adapt to this new mode of transport. Despite challenges, e-scooters are changing urban mobility."},
                {"Exploring the Ethical Implications of AI", "As AI continues to advance, ethical questions regarding its application are gaining attention. Concerns include bias in algorithms, privacy issues, and the potential loss of jobs. Experts argue that ethical guidelines and regulations are essential to ensure AI development benefits society as a whole and minimizes harm."},
                {"Climate Policy and Global Cooperation","Global cooperation is essential to address climate change, as countries work towards emission reduction goals. International agreements, like the Paris Accord, set targets for reducing greenhouse gases. Despite differences in economic interests, cooperation is necessary to prevent catastrophic environmental impacts and protect future generations."},
                {"The Role of Virtual Reality in Education",  "Virtual reality is becoming an innovative tool in education, allowing students to experience immersive learning. VR helps with subjects like history, science, and geography by simulating real-world scenarios. As costs decrease, VR could become a standard tool in classrooms, making learning more engaging and accessible."},
                {"Food Security and Agricultural Technology", "Technological advances in agriculture are critical for food security. Precision farming, GM crops, and AI-driven analytics are helping farmers increase yield and efficiency. As climate change threatens crop yields, investing in sustainable agriculture technology is essential to ensure a stable food supply for the global population."},
                {"Rise of Telemedicine During the Pandemic","Telemedicine surged during the COVID-19 pandemic as healthcare providers sought safe ways to deliver care. Patients could access medical consultations remotely, reducing the risk of infection. Although in-person visits remain essential, telemedicine is expected to continue as an accessible option for routine healthcare."},
                {"Blockchain in Supply Chain Management",  "Blockchain technology is improving transparency and traceability in supply chain management. By recording each step in the chain, companies can reduce fraud and enhance accountability. This technology also helps with inventory management and regulatory compliance, benefiting sectors like food and pharmaceuticals that rely on strict monitoring."},
                {"Electric Planes: Future of Air Travel", "The development of electric planes promises a more sustainable future for air travel. Companies are investing in electric propulsion technologies to reduce carbon emissions and reliance on fossil fuels. While still in the early stages, electric planes could revolutionize short-haul flights, offering an eco-friendly alternative to traditional aviation."},
                {"AI and Automation in Customer Service", "Companies are increasingly using AI and automation to enhance customer service. Chatbots and virtual assistants handle routine queries, allowing human agents to focus on complex issues. While automation improves efficiency, businesses must balance it with a personal touch to ensure customer satisfaction and prevent service quality declines."},
                {"Privacy Concerns with Smart Home Devices",  "Smart home devices, from speakers to security cameras, offer convenience but raise privacy concerns. These devices collect data, often with limited transparency on how it's used. Consumers are urged to take precautions, such as changing default settings and understanding device privacy policies, to protect personal information."},
                {"Wearable Technology in Health Monitoring", "Wearable health tech, like fitness trackers and smartwatches, allows users to monitor their health in real-time. Devices can track heart rate, sleep patterns, and more, offering insights into personal health. The rise of wearables reflects a shift toward preventive healthcare, with potential benefits for early disease detection."},
                {"Carbon Capture: An Answer to Emissions?","Carbon capture technology is seen as a solution to reduce greenhouse gas emissions. It involves capturing carbon dioxide from the air and storing it underground. While promising, critics argue that it may not be enough to combat climate change without broader emission reductions across industries."},
                {"The Economics of Climate Change", "Climate change poses economic risks, from damaged infrastructure to disrupted agriculture. Economists warn that failure to address climate change could lead to substantial financial costs. Countries are urged to adopt sustainable practices and invest in resilience measures to protect their economies from climate-related disruptions."},
                {"Online Education and the Digital Divide",  "The rise of online education during the pandemic highlighted disparities in access to technology. Students in rural or low-income areas often lack reliable internet, creating a digital divide. Addressing this issue is essential to ensure equal educational opportunities and prevent widening achievement gaps."},
                {"Artificial Intelligence in Healthcare","Artificial Intelligence (AI) has emerged as a powerful tool in healthcare, assisting doctors with diagnosis, treatment recommendations, and patient monitoring. AI algorithms can analyze medical images, identify patterns, and predict outcomes, significantly improving efficiency and accuracy in patient care. While AI holds great potential, its widespread adoption in healthcare still faces challenges related to data privacy, ethics, and regulatory approval."},
                {"Automation in Manufacturing: A Game Changer","Automation is revolutionizing the manufacturing industry by improving production efficiency, reducing costs, and minimizing human errors. With the integration of robotics, AI, and machine learning, manufacturers are able to produce high-quality products at a faster rate. However, the shift toward automation raises concerns about job displacement and the need for workers to acquire new skills."},
                {"Impact of Artificial Intelligence on Employment", "AI's increasing role in the workplace has led to both excitement and concern. On the one hand, AI has the potential to create new jobs and improve productivity. On the other hand, there are fears that automation will lead to widespread job loss, particularly in industries that rely heavily on routine tasks. The future of work will require a balance between leveraging AI’s potential and ensuring economic stability for workers."},
                {"The Ethics of Autonomous Vehicles", "Autonomous vehicles (AVs) are changing the landscape of transportation, offering benefits such as improved safety, reduced traffic, and less environmental impact. However, ethical issues arise when it comes to decision-making in life-or-death situations. Who is responsible when an AV makes a controversial decision? As AV technology advances, it will be critical to develop ethical frameworks to guide their use on public roads."},
                {"Sustainable Fashion: The Future of the Industry", "Sustainable fashion is gaining popularity as consumers and brands alike recognize the environmental and ethical challenges posed by fast fashion. From eco-friendly materials to ethical labor practices, the industry is evolving to meet the demands of a more conscious consumer base. However, the transition to sustainability requires significant changes in production processes and consumer behavior."},
                {"The Role of Artificial Intelligence in Marketing","AI is transforming the marketing industry by enabling more personalized, efficient, and data-driven campaigns. Marketers are leveraging AI to analyze consumer behavior, optimize content delivery, and predict trends. AI-powered tools also assist in customer segmentation and targeted advertising. While AI can increase marketing effectiveness, it also raises concerns about privacy and data security."},
                {"Electric Vehicles: The Path to a Greener Future",  "Electric vehicles (EVs) are gaining traction as a sustainable alternative to gasoline-powered cars. EVs reduce carbon emissions, improve air quality, and decrease reliance on fossil fuels. However, challenges such as charging infrastructure, battery life, and manufacturing costs must be addressed to make EVs more accessible to the mass market. The shift toward electric transportation is a crucial step in combating climate change."},
                {"The Future of Augmented Reality in Retail", "Augmented Reality (AR) is transforming the retail experience by allowing customers to try on products virtually, visualize items in their homes, and make more informed purchasing decisions. Retailers are increasingly integrating AR into their stores and websites, creating immersive experiences that engage consumers in new ways. As AR technology advances, its impact on retail is expected to grow exponentially."},
                {"The Rise of Smart Cities","Smart cities are the next evolution of urban living, where technology and data are used to improve the quality of life for residents. From traffic management to energy efficiency, smart cities utilize sensors, data analytics, and IoT devices to optimize urban services and infrastructure. While smart cities offer numerous benefits, they also raise concerns about privacy, data security, and the digital divide."},
                {"The Role of Artificial Intelligence in Education", "Artificial Intelligence (AI) is increasingly being integrated into education to improve learning outcomes and personalize instruction. AI-powered tools can help educators identify student strengths and weaknesses, create tailored learning plans, and automate administrative tasks. However, the use of AI in education also raises ethical concerns about data privacy and the potential for bias in algorithms."},
                {"Women's Soccer Sees Unprecedented Growth and Recognition", "Women's soccer is experiencing a surge in popularity, with record-breaking attendance and increased investment in leagues worldwide. This growth is seen as a positive step for gender equality in sports, encouraging young female athletes and driving more attention toward the women's game. Alongside fan interest, sponsorships and media coverage are growing, signaling that women’s soccer is stepping into the mainstream spotlight, though equal pay and recognition are still ongoing discussions within the industry."},
                {"Volatile Stock Market Reflects Economic Uncertainty Amid Global Pressures", "Stock markets worldwide have been highly volatile due to economic uncertainty driven by inflation, interest rate hikes, and geopolitical tensions. Investors face challenges as they balance risks in an unpredictable market environment. Financial experts urge caution, advising diversified investment strategies as markets adjust to shifting consumer demands, supply chain disruptions, and policy changes impacting the global economy. Analysts are closely watching sectors like tech and energy, where volatility has been pronounced."},
                {"Climate Change Linked to Intensified Storm Patterns", "New research reveals that climate change is causing more intense and frequent storms, increasing damage to vulnerable communities. Researchers emphasize the need for immediate climate action to mitigate further risks, as warmer oceans and changing atmospheric conditions fuel stronger storms. Governments are encouraged to adopt policies focused on climate resilience, including infrastructure improvements and sustainable land-use practices, to better protect regions at high risk for natural disasters."},
                {"Startups Pave the Way for Innovation in Renewable Energy Technology", "Tech startups are at the forefront of renewable energy innovation, with breakthroughs in solar, wind, and battery storage technologies promising a more sustainable future. These companies aim to make clean energy more affordable and accessible, driving a shift toward renewables in both developed and developing countries. Industry experts see these startups as pivotal players in the global transition away from fossil fuels, with many partnering with established energy firms to bring their technologies to a broader market."},
                {"AI in Healthcare: Enhancing Diagnostic Capabilities and Improving Patient Outcomes", "Artificial intelligence is transforming healthcare by enhancing diagnostic accuracy, particularly in radiology and pathology. AI algorithms can quickly analyze medical images, detect early signs of diseases like cancer, and improve patient outcomes. Despite the promise, the integration of AI in healthcare raises ethical questions, particularly around data privacy and regulatory hurdles. As AI becomes more widely used in hospitals, healthcare professionals are calling for clear guidelines to balance innovation with patient safety."},
                {"Global Climate Summit Calls for Renewed Commitments to Emission Reductions", "World leaders gathered at the latest climate summit to address the escalating threat of climate change. The event underscored the importance of international cooperation, as representatives discussed carbon reduction goals and sustainable development strategies. While some countries committed to ambitious targets, others faced criticism for limited action. The summit highlighted the need for stronger commitments and immediate implementation to mitigate future environmental impacts."},
                {"Online Learning Platforms Revolutionize Access to Education", "The growth of online learning platforms is reshaping education, providing greater accessibility to resources for students across the globe. Many institutions are adapting to a hybrid model that combines in-person and online instruction. However, challenges such as access to reliable internet and adequate devices for students in remote areas remain. As more students embrace the flexibility of online learning, education experts emphasize the need to bridge digital divides to ensure equitable access for all."},
                {"Olympics to Introduce Skateboarding and Surfing to Appeal to Younger Audiences", "The upcoming Olympic Games will include skateboarding and surfing, reflecting a shift toward sports that resonate with younger audiences. The decision to introduce these sports is part of an effort to make the Olympics more inclusive and diverse, aligning with changing global interests. Organizers hope this evolution will attract new fans, though traditionalists remain divided on the inclusion of unconventional sports in the Olympic roster."},
                {"E-commerce Revolution Offers Small Businesses a Lifeline", "The rapid rise of e-commerce has empowered small businesses by providing them with direct access to a global market. Small enterprises that once relied on local foot traffic now find growth opportunities online, with digital marketing and online storefronts becoming essential for survival. However, increased competition and the need for strong digital skills present challenges. Industry experts predict that e-commerce will continue to evolve, with small businesses embracing new technologies to stay competitive."},
                {"Study Shows Rising Temperatures Increase Public Health Risks", "A new study links rising global temperatures with increased health risks, particularly for the elderly and those with preexisting conditions. Heatwaves and extreme weather events are causing higher incidences of heat-related illnesses, such as dehydration and heatstroke. Public health officials are emphasizing the need for community-based interventions, including public cooling centers and health advisories, to help vulnerable populations cope with extreme temperatures."},
                {"Tech Giants Embrace AI for Content Creation", "Major tech companies are developing AI tools for writing and design, revolutionizing content creation. This trend raises debates over intellectual property and the future of human creativity. Industry leaders are working on ethical standards to guide responsible AI usage in digital content production."},
                {"The Future of Space Tourism", "Space tourism is shifting from sci-fi to reality as private companies launch space flights for civilians. Although prohibitively expensive for most, the sector is expected to grow as costs decrease. Space tourism could reshape our understanding of space, yet regulatory and environmental concerns remain crucial as the industry evolves."},
                {"Cybersecurity Threats in 2024", "Cybersecurity is a growing priority as digital threats continue to evolve. With more companies shifting to remote work, vulnerabilities have increased, requiring updated defenses. Hackers exploit weak systems, and companies invest in measures like encryption and multi-factor authentication. Governments are also drafting laws to combat cyber threats effectively."},
                {"Impact of Social Media on Mental Health", "Social media is reshaping our social lives, but its impact on mental health is significant. Studies indicate high social media usage correlates with anxiety, depression, and self-esteem issues, particularly among youth. To mitigate these effects, platforms are exploring features that promote positive engagement and reduce harmful content."},
                {"Climate Change and Extreme Weather Events", "The frequency of extreme weather events, including hurricanes, floods, and wildfires, has risen due to climate change. Scientists warn that unless emissions are curbed, these events will become more common. Nations are urged to adopt green policies to combat these changes and protect vulnerable communities from climate-related disasters."},
                {"Electric Cars Transform Urban Mobility", "Electric cars are becoming more popular, especially in cities. With better charging infrastructure, governments and carmakers are pushing for a shift to electric vehicles. The transition is beneficial for the environment, but challenges like battery disposal and charging accessibility remain to be addressed for a sustainable future."},
                {"5G Technology Revolutionizing Industries", "5G technology is being implemented globally, promising faster internet speeds and lower latency. This shift will enable new possibilities in IoT, healthcare, and remote work. However, deploying 5G infrastructure is challenging and costly, and some regions are lagging. Nonetheless, 5G holds transformative potential across industries."},
                {"Advancements in Quantum Computing", "Quantum computing is emerging as a game-changer in data processing. Unlike traditional computers, quantum computers use quantum bits to perform complex calculations faster. The technology is still in its infancy but holds promise for breakthroughs in cryptography, material science, and artificial intelligence."},
                {"The Growing Popularity of Plant-Based Diets", "Plant-based diets are gaining traction as more people seek sustainable and ethical eating habits. Many studies link plant-based diets to better health outcomes and reduced environmental impact. While transitioning to such diets can be challenging, the availability of plant-based products is making it easier."},
                {"Cryptocurrency Regulations and Market Impact", "Governments are tightening cryptocurrency regulations in response to market volatility and security concerns. While regulations aim to protect investors, they also pose challenges for market innovation. Some argue that sensible regulations will help cryptocurrency thrive, while others worry they could stifle the decentralized nature of digital currencies."},
                {"E-Commerce Trends in 2024", "The e-commerce sector continues to evolve, with trends such as same-day delivery, personalized shopping experiences, and increased use of artificial intelligence. Retailers are investing in technologies that enhance customer experience. As competition grows, companies are focusing on sustainable practices and social responsibility to attract modern consumers."},
                {"Rise of Electric Scooters in Cities", "Electric scooters have become a common sight in cities around the world. They offer an eco-friendly alternative to cars, reducing congestion and emissions. However, safety concerns and regulations vary widely, with some cities struggling to adapt to this new mode of transport. Despite challenges, e-scooters are changing urban mobility."},
                {"Exploring the Ethical Implications of AI", "As AI continues to advance, ethical questions regarding its application are gaining attention. Concerns include bias in algorithms, privacy issues, and the potential loss of jobs. Experts argue that ethical guidelines and regulations are essential to ensure AI development benefits society as a whole and minimizes harm."},
                {"Climate Policy and Global Cooperation", "Global cooperation is essential to address climate change, as countries work towards emission reduction goals. International agreements, like the Paris Accord, set targets for reducing greenhouse gases. Despite differences in economic interests, cooperation is necessary to prevent catastrophic environmental impacts and protect future generations."},
                {"The Role of Virtual Reality in Education", "Virtual reality is becoming an innovative tool in education, allowing students to experience immersive learning. VR helps with subjects like history, science, and geography by simulating real-world scenarios. As costs decrease, VR could become a standard tool in classrooms, making learning more engaging and accessible."},
                {"Food Security and Agricultural Technology", "Technological advances in agriculture are critical for food security. Precision farming, GM crops, and AI-driven analytics are helping farmers increase yield and efficiency. As climate change threatens crop yields, investing in sustainable agriculture technology is essential to ensure a stable food supply for the global population."},
                {"Rise of Telemedicine During the Pandemic", "Telemedicine surged during the COVID-19 pandemic as healthcare providers sought safe ways to deliver care. Patients could consult doctors remotely, improving access to care, especially for rural populations. Although telemedicine has challenges, such as technology limitations, it's expected to remain a valuable tool in healthcare."},
                {"The Importance of Data Privacy in 2024", "Data privacy concerns are rising as digital activities increase. Governments worldwide are enacting stricter regulations, such as the GDPR, to protect consumer information. Businesses are also updating policies to comply with privacy laws. As technology evolves, balancing innovation with privacy protection remains a key challenge."},
                {"Space Exploration and the Race to Mars", "Interest in Mars exploration is intensifying, with private companies and space agencies investing in missions to the Red Planet. These missions aim to study Mars for potential human colonization and scientific discovery. While progress is being made, challenges related to cost, safety, and sustainability remain significant."},
                {"Smart Cities: The Future of Urban Living", "Smart cities are transforming urban living by integrating technology into infrastructure. With IoT and AI, cities aim to enhance public services, reduce waste, and improve citizens' quality of life. However, building smart cities requires significant investment and poses privacy concerns due to increased surveillance."},
                {"Renewable Energy as a Climate Solution", "Renewable energy sources like wind and solar are gaining popularity as climate change pressures increase. Governments are investing in green energy to reduce carbon emissions. Transitioning to renewables has challenges, such as cost and storage capacity, but experts see it as crucial for a sustainable future."},
                {"The Rise of Remote Work and Its Impact on Work-Life Balance", "The rise of remote work is reshaping work-life balance. While employees enjoy flexibility, challenges like isolation and blurred boundaries between work and personal life arise. Companies are experimenting with policies that support remote work, yet balance remains key for long-term success in remote work culture."},
                {"Microplastics and Their Environmental Impact", "Microplastics have become a significant environmental concern, polluting oceans and harming marine life. Studies show that microplastics are found even in remote areas. Governments and environmental organizations are working to reduce plastic waste and protect ecosystems from the detrimental effects of microplastics."},
                {"Impact of Cryptocurrency on the Financial Sector", "Cryptocurrency is disrupting traditional finance, offering a decentralized alternative to banks. Many institutions are cautiously adopting digital currencies, while others raise concerns over volatility and regulation. As crypto becomes mainstream, its impact on the financial sector is expected to grow."},
                {"The Mental Health Crisis in the Post-Pandemic World", "The COVID-19 pandemic has left a lasting impact on mental health, with more people experiencing anxiety, depression, and stress. Mental health services are in high demand, and experts advocate for more accessible resources and societal acceptance to address the mental health crisis effectively."},
                {"Increasing Popularity of Wearable Health Technology", "Wearable devices that monitor health, like heart rate and sleep quality, are becoming mainstream. With advancements in tech, wearables are helping people manage their health and detect early signs of illness. However, concerns over data privacy and accuracy persist, requiring regulation and development."},
                {"The Push for Diversity in STEM Fields", "Efforts to increase diversity in STEM are gaining momentum, with initiatives to encourage underrepresented groups to pursue science and technology careers. Companies and schools are addressing gender and racial gaps, recognizing that a diverse workforce fosters innovation and better problem-solving."},
                {"The Growing Threat of Ransomware", "Ransomware attacks are on the rise, targeting governments, hospitals, and businesses. Hackers use ransomware to hold data hostage, demanding payments for its release. Cybersecurity experts stress the need for stronger defenses and collaboration between law enforcement and organizations to combat ransomware."},
                {"The Decline of Print Media and Rise of Digital Journalism", "As digital media grows, print journalism is experiencing a decline. Readers are moving online for instant access to news, forcing traditional outlets to adapt. While digital journalism offers convenience, it also faces challenges like misinformation and finding sustainable revenue models."},
                {"AI and the Future of Personalized Marketing", "Artificial intelligence is revolutionizing marketing by personalizing customer experiences. AI tools analyze data to predict consumer preferences, enabling targeted ads. Although effective, some consumers find personalized ads intrusive, sparking debates on privacy and ethical data usage in marketing."},
                {"The Role of Green Technology in Sustainability", "Green technology is essential for sustainable development, with innovations in renewable energy, waste management, and eco-friendly materials. Governments are supporting green tech startups, recognizing the role of technology in addressing environmental issues. As demand grows, green tech is expected to transform industries."},
                {"The Effects of Climate Change on Wildlife", "Climate change is impacting wildlife, with animals facing habitat loss and changing migration patterns. Many species are adapting, but others are at risk of extinction. Conservationists are working to protect vulnerable ecosystems, calling for global action to mitigate climate change and preserve biodiversity."},
                {"Urban Farming: A Sustainable Solution for Food Production", "Urban farming is gaining popularity as cities look for sustainable food solutions. Rooftop gardens and vertical farms reduce food transportation costs and carbon emissions. Although challenges like space limitations exist, urban farming is seen as a promising solution for food security and sustainability."},
                {"Developments in Battery Technology for Electric Vehicles", "Advances in battery technology are making electric vehicles more efficient and affordable. New batteries with longer life and faster charging capabilities are in development, reducing 'range anxiety.' With these innovations, electric cars are expected to become a more viable alternative to gasoline vehicles."},
                {"The Influence of Social Media on Political Movements", "Social media platforms play a crucial role in political movements, amplifying voices and organizing protests. While social media increases awareness, it also spreads misinformation. Activists use it to mobilize supporters, but there are concerns over censorship and the influence of social media giants on public opinion."},
                {"The Impact of Automation on the Global Economy", "Automation is transforming industries worldwide, increasing productivity but also threatening jobs in sectors like manufacturing and transportation. Economists warn that without policies to support displaced workers, automation could deepen income inequality. Retraining programs and social safety nets are essential as automation advances."},
                {"Ocean Conservation Efforts Gain Momentum", "Ocean conservation is becoming a priority as pollution and overfishing threaten marine ecosystems. Initiatives like marine protected areas and policies to reduce plastic waste are being implemented. Conservationists stress that saving the oceans is crucial for biodiversity and combating climate change."},
                {"5G and the Future of Smart Cities", "The rollout of 5G networks is accelerating the development of smart cities. 5G enables faster data transmission for IoT devices, improving urban infrastructure and services. While smart cities promise efficiency and convenience, concerns about data privacy and security continue to challenge their implementation."},
                {"The Rising Popularity of Digital Nomadism", "Digital nomadism is becoming popular as remote work allows employees to work from anywhere. Many people embrace the flexibility of traveling while working, though challenges like visa restrictions and internet connectivity remain. Companies are adapting to support a more mobile workforce."},
                {"The Rise of Minimalism as a Lifestyle Choice", "Minimalism is gaining popularity as people seek simplicity and reduce consumption. Advocates of minimalism say it leads to greater mental clarity and financial freedom. While not for everyone, the movement reflects a shift towards sustainable living and mindful consumerism."},
                {"Mental Health and Wellbeing in the Workplace", "The focus on employee mental health and well-being is increasing as more organizations recognize its impact on productivity. Companies are implementing mental health programs, flexible work schedules, and counseling services. Addressing workplace mental health is crucial to creating supportive work environments."},
                {"AI's Role in Enhancing Customer Service Automation", "Artificial Intelligence is revolutionizing customer service by automating responses, enabling businesses to deliver faster and more personalized service. AI-driven chatbots and virtual assistants are now common in industries such as banking, retail, and telecom. While automation reduces wait times, there are concerns about job displacement in customer support roles. However, many experts argue that AI can augment human workers rather than replace them, allowing for more complex problem-solving."},
                {"The Impact of Sustainability on Fashion Industry Trends", "Sustainability has become a key factor driving change in the fashion industry, with brands increasingly prioritizing eco-friendly materials and ethical manufacturing processes. From recycled fabrics to carbon-neutral production, the fashion world is responding to consumer demand for more sustainable products. However, challenges remain in scaling these practices while keeping products affordable, leading to a growing conversation about the future of fast fashion."},
                {"Virtual Reality Transforming Healthcare Education", "Virtual reality (VR) is revolutionizing medical education, providing students with immersive experiences that simulate real-life procedures and anatomy. VR technology enables medical professionals to practice surgical techniques and diagnose diseases in a risk-free environment. As VR adoption grows in medical schools, it is expected to improve patient care by better preparing doctors and nurses for real-world scenarios."},
                {"The Future of Autonomous Vehicles in Urban Planning", "Autonomous vehicles are poised to reshape urban planning as they promise to reduce traffic congestion, lower accident rates, and create new transportation systems. Cities are already exploring ways to integrate self-driving cars into their infrastructure. While the technology holds great potential, regulatory challenges, as well as safety concerns, continue to pose barriers to large-scale deployment."},
                {"5G's Impact on IoT and the Connected World", "The advent of 5G technology is set to transform the Internet of Things (IoT) by enabling faster, more reliable connections for connected devices. From smart homes to industrial automation, 5G offers the bandwidth necessary to support an exponentially growing network of devices. However, 5G's rollout presents challenges in terms of infrastructure, costs, and privacy concerns surrounding the vast amounts of data generated by these devices."},
                {"The Growth of Online Mental Health Services", "The demand for online mental health services has surged in recent years, especially during the COVID-19 pandemic. Platforms offering therapy, counseling, and support groups have made mental health care more accessible, especially for those in remote areas. While the convenience of virtual care is undeniable, concerns over the effectiveness of online treatment, data privacy, and the digital divide remain significant."},
                {"The Role of Technology in Modern Agriculture", "Technology is revolutionizing agriculture with innovations such as drones, sensors, and AI-driven analytics that help farmers increase crop yields, monitor soil health, and optimize water usage. Precision farming technologies allow for more efficient resource management, but challenges remain in terms of affordability and access for small-scale farmers. Despite these obstacles, technological advancements are seen as essential for feeding a growing global population."},
                {"Social Media's Influence on Youth Culture", "Social media plays a significant role in shaping youth culture, influencing everything from fashion trends to political beliefs. Platforms like Instagram, TikTok, and YouTube allow young people to share ideas and express themselves creatively, but they also raise concerns about cyberbullying, body image issues, and online addiction. Parents, educators, and policymakers are increasingly involved in discussions about how to ensure that social media is used safely and responsibly."},
                {"The Growing Need for Cybersecurity in the Age of Data Breaches", "As cyberattacks become more sophisticated, businesses and governments are investing heavily in cybersecurity measures to protect sensitive data. With high-profile data breaches becoming more frequent, organizations must ensure that their systems are equipped to prevent unauthorized access. Security experts emphasize the importance of constant vigilance and educating employees about phishing and other types of cyber threats."},
                {"Cryptocurrency's Growing Role in Global Finance", "Cryptocurrency is becoming an increasingly significant player in global finance, offering an alternative to traditional currencies and payment systems. Digital assets like Bitcoin and Ethereum are attracting investors, while governments are exploring regulatory frameworks to manage their use. Despite volatility and concerns over fraud, cryptocurrency is seen as having the potential to revolutionize the financial industry."},
                {"The Evolution of Smart Homes and Their Future Impact", "Smart homes are becoming more common as consumers adopt connected devices like thermostats, lights, and security cameras. These technologies offer greater convenience, energy efficiency, and security, but concerns about privacy and data security are growing. As smart homes become more integrated into daily life, experts predict that the next phase will involve even more advanced AI systems that anticipate user needs and optimize household functions."},
                {"Electric Aviation: The Future of Sustainable Air Travel", "Electric aviation is emerging as a promising solution to reduce the carbon footprint of air travel. Several startups and established aerospace companies are working on electric aircraft that aim to lower emissions and operating costs. While challenges such as battery limitations and high development costs remain, electric planes are expected to play a significant role in making air travel more sustainable in the coming decades."},
                {"The Impact of AI in Personalized Education", "Artificial intelligence is transforming education by enabling personalized learning experiences tailored to individual student needs. AI-powered platforms can assess students’ strengths and weaknesses, adapt lessons, and provide real-time feedback. Although AI holds great promise in improving educational outcomes, concerns about the data privacy of students and the potential for algorithmic bias remain key issues."},
                {"Telemedicine's Role in Expanding Healthcare Access", "Telemedicine is playing an increasingly important role in expanding access to healthcare, particularly in rural and underserved areas. Patients can now consult doctors remotely, making healthcare more accessible for those who may not have nearby medical facilities. While telemedicine has many benefits, such as reducing wait times and improving convenience, challenges like technological barriers and reimbursement issues still need to be addressed."},
                {"The Future of Digital Payments and the Cashless Society", "Digital payments are rapidly replacing cash transactions as consumers and businesses alike embrace mobile wallets, contactless payments, and cryptocurrency. With the rise of mobile payment apps and e-commerce platforms, the world is moving closer to a cashless society. However, issues like fraud prevention, digital inequality, and privacy concerns remain critical challenges in the adoption of cashless systems."},
                {"Electric Cars and the Push for Sustainable Urban Transportation", "Electric vehicles (EVs) are gaining traction as cities seek sustainable alternatives to traditional gasoline-powered cars. With government incentives, advancements in battery technology, and growing public awareness of environmental issues, EVs are becoming a viable option for urban transportation. However, the widespread adoption of electric vehicles faces challenges, such as infrastructure development, high initial costs, and concerns about battery disposal."},
                {"Advancements in Genetic Editing and Ethical Dilemmas", "CRISPR and other genetic editing technologies are making it possible to alter the DNA of organisms with unprecedented precision. These advancements hold great promise for curing genetic diseases and enhancing agriculture, but they also raise ethical concerns about the potential misuse of the technology. As genetic editing continues to evolve, debates over its implications for human genetics and biodiversity are intensifying."},
                {"The Role of Data Analytics in Enhancing Sports Performance", "Data analytics is transforming the sports industry, helping athletes and teams optimize performance through the analysis of big data. By using sensors and tracking technologies, coaches can gain insights into players' movements, fitness levels, and injury risks. While data analytics has the potential to revolutionize sports training, there are concerns about privacy and the over-reliance on data in decision-making."},
                {"The Impact of Automation on Job Creation and Job Loss", "As automation continues to advance, there are growing concerns about its impact on the labor market. While automation can increase productivity and reduce costs, it may also lead to job displacement in sectors like manufacturing, retail, and logistics. Policymakers are being urged to implement strategies that provide workers with the skills needed to adapt to the changing job landscape, such as reskilling programs and universal basic income."},
                {"The Rise of Remote Work and Its Long-Term Effects", "Remote work, which gained popularity during the COVID-19 pandemic, is here to stay for many organizations and employees. While remote work offers greater flexibility and work-life balance, it also presents challenges in terms of collaboration, communication, and maintaining company culture. Experts predict that hybrid work models will become more common as businesses seek to balance the benefits of remote work with the need for in-person collaboration."},
                {"The Potential of Blockchain Beyond Cryptocurrency", "Blockchain technology, originally developed to support cryptocurrency transactions, is finding applications beyond the financial sector. From supply chain management to healthcare data security, blockchain offers a decentralized, transparent system for securely sharing information. As businesses and governments explore the technology’s potential, blockchain is expected to revolutionize various industries by improving efficiency, trust, and data security."},
                {"The Rise of Electric Bikes as a Sustainable Transport Option", "Electric bikes (e-bikes) are gaining popularity as an environmentally friendly alternative to traditional transportation. With their ability to reduce traffic congestion and lower carbon emissions, e-bikes are becoming a preferred mode of transport in urban areas. Despite their benefits, challenges such as high upfront costs and the need for better cycling infrastructure remain as obstacles to wider adoption."},
                {"Technology and the Future of Personalized Healthcare", "Advancements in personalized healthcare, driven by data analytics, AI, and genomics, are enabling more tailored treatments for patients. By analyzing individual genetic profiles, lifestyle factors, and health data, healthcare providers can offer customized care that improves patient outcomes. However, concerns about data privacy, access to personalized care, and the cost of these innovations remain important challenges."},
                {"The Role of Artificial Intelligence in Predicting Natural Disasters", "AI is playing an increasingly important role in predicting natural disasters by analyzing patterns in environmental data. From earthquakes to hurricanes, AI systems can help improve early warning systems, allowing for more timely evacuations and response efforts. While AI has the potential to save lives, it also faces challenges in terms of data accuracy and the ability to predict unpredictable events."},
                {"Advancements in Solar Power Technology", "Solar power is rapidly evolving, with new innovations making it more efficient and affordable. From solar panels that capture more sunlight to energy storage solutions that allow for round-the-clock use, solar energy is becoming a key component of the global shift toward renewable energy. As solar power technology advances, the challenges of energy storage and grid integration remain crucial for large-scale adoption."},
                {"The Growth of E-commerce and Its Impact on Traditional Retail", "The rapid growth of e-commerce is reshaping the retail landscape, with more consumers choosing to shop online instead of in physical stores. As e-commerce platforms grow, traditional retailers are facing challenges in maintaining foot traffic and adapting to digital sales strategies. Despite these hurdles, many brick-and-mortar stores are embracing e-commerce to stay competitive in the changing market."},
                {"The Promise and Perils of Quantum Computing", "Quantum computing promises to revolutionize fields such as cryptography, materials science, and drug discovery. With its ability to solve complex problems at speeds unimaginable for classical computers, quantum computing holds the potential to unlock new scientific and technological frontiers. However, the technology is still in its infancy, and experts caution that significant breakthroughs are needed before quantum computers can be widely used."},
                {"The Global Shift Toward Renewable Energy Investment", "As the world faces the impacts of climate change, governments and businesses are increasingly investing in renewable energy sources such as wind, solar, and hydroelectric power. These investments are expected to reduce reliance on fossil fuels and mitigate environmental damage. While challenges remain in scaling up renewable energy infrastructure, the growing commitment to sustainability is driving change in the global energy market."},
                {"Telecommunications and the Future of 5G Connectivity", "5G technology is expected to revolutionize telecommunications by offering faster internet speeds, lower latency, and more reliable connections. This next-generation network will enable innovations in IoT, autonomous vehicles, and augmented reality, making it a key enabler of the digital economy. However, challenges related to infrastructure, spectrum allocation, and security must be addressed before 5G can reach its full potential."},

        };
        String url = "jdbc:mysql://localhost:3306/news";
        String user = "root";
        String password = "Dulina@123";





        String insertSQL = "INSERT INTO article (title, content, category) VALUES (?, ?, ?)"+ "ON DUPLICATE KEY UPDATE content = ?, category = ?";;

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            try (PreparedStatement statement = connection.prepareStatement(insertSQL)) {
                for (String[] article : articles) {
                    String title = article[0];
                    String content = article[1];

                    KeywordExtraction keywordExtraction = new KeywordExtraction();
                    String category = keywordExtraction.categorizeArticle(article[1]);


                    statement.setString(1, title);
                    statement.setString(2, content);
                    statement.setString(3, category);
                    statement.setString(4, content);
                    statement.setString(5, category);

                    statement.executeUpdate();
                }

                System.out.println("Articles inserted successfully.");
            } catch (SQLException e) {
                System.out.println("Error while inserting data: " + e.getMessage());
            }
        } catch (SQLException e) {
            System.out.println("Connection failed: " + e.getMessage());
        }
    }


}