package com.example.cw1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;

public class ArticleInserter {
    public static void main(String[] args) {
        String[][] articles = {
                {"Tech Giants Embrace AI for Content Creation","Major tech companies are developing AI tools for writing and design, revolutionizing content creation. This trend raises debates over intellectual property and the future of human creativity. Industry leaders are working on ethical standards to guide responsible AI usage in digital content production."},
                {"Renewable Energy Gains Momentum Globally","Renewable energy sources, including wind, solar, and hydropower, are now key to sustainable development. Countries are committing to lower carbon emissions, investing in clean energy technology. However, renewable energy faces challenges like intermittency, but technological advancements are slowly overcoming these issues. Increased adoption rates are promising for a future with minimal carbon footprint."},
                {"The Future of Space Tourism","Space tourism is shifting from sci-fi to reality as private companies launch space flights for civilians. Although prohibitively expensive for most, the sector is expected to grow as costs decrease. Space tourism could reshape our understanding of space, yet regulatory and environmental concerns remain crucial as the industry evolves."},
                {"Cybersecurity Threats in 2024","Cybersecurity is a growing priority as digital threats continue to evolve. With more companies shifting to remote work, vulnerabilities have increased, requiring updated defenses. Hackers exploit weak systems, and companies invest in measures like encryption and multi-factor authentication. Governments are also drafting laws to combat cyber threats effectively."},
                {"Impact of Social Media on Mental Health","Social media is reshaping our social lives, but its impact on mental health is significant. Studies indicate high social media usage correlates with anxiety, depression, and self-esteem issues, particularly among youth. To mitigate these effects, platforms are exploring features that promote positive engagement and reduce harmful content."},
                {"Climate Change and Extreme Weather Events","The frequency of extreme weather events, including hurricanes, floods, and wildfires, has risen due to climate change. Scientists warn that unless emissions are curbed, these events will become more common. Nations are urged to adopt green policies to combat these changes and protect vulnerable communities from climate-related disasters."},
                {"Electric Cars Transform Urban Mobility","Electric cars are becoming more popular, especially in cities. With better charging infrastructure, governments and carmakers are pushing for a shift to electric vehicles. The transition is beneficial for the environment, but challenges like battery disposal and charging accessibility remain to be addressed for a sustainable future."},
                {"5G Technology Revolutionizing Industries","5G technology is being implemented globally, promising faster internet speeds and lower latency. This shift will enable new possibilities in IoT, healthcare, and remote work. However, deploying 5G infrastructure is challenging and costly, and some regions are lagging. Nonetheless, 5G holds transformative potential across industries."},
                {"Advancements in Quantum Computing", "Quantum computing is emerging as a game-changer in data processing. Unlike traditional computers, quantum computers use quantum bits to perform complex calculations faster. The technology is still in its infancy but holds promise for breakthroughs in cryptography, material science, and artificial intelligence."},
                {"The Growing Popularity of Plant-Based Diets","Plant-based diets are gaining traction as more people seek sustainable and ethical eating habits. Many studies link plant-based diets to better health outcomes and reduced environmental impact. While transitioning to such diets can be challenging, the availability of plant-based products is making it easier."},
                {"Cryptocurrency Regulations and Market Impact", "Governments are tightening cryptocurrency regulations in response to market volatility and security concerns. While regulations aim to protect investors, they also pose challenges for market innovation. Some argue that sensible regulations will help cryptocurrency thrive, while others worry they could stifle the decentralized nature of digital currencies."},
                {"E-Commerce Trends in 2024", "The e-commerce sector continues to evolve, with trends such as same-day delivery, personalized shopping experiences, and increased use of artificial intelligence. Retailers are investing in technologies that enhance customer experience. As competition grows, companies are focusing on sustainable practices and social responsibility to attract modern consumers."},
                {"Rise of Electric Scooters in Cities","Electric scooters have become a common sight in cities around the world. They offer an eco-friendly alternative to cars, reducing congestion and emissions. However, safety concerns and regulations vary widely, with some cities struggling to adapt to this new mode of transport. Despite challenges, e-scooters are changing urban mobility."},
                {"Exploring the Ethical Implications of AI", "As AI continues to advance, ethical questions regarding its application are gaining attention. Concerns include bias in algorithms, privacy issues, and the potential loss of jobs. Experts argue that ethical guidelines and regulations are essential to ensure AI development benefits society as a whole and minimizes harm."},
                {"Climate Policy and Global Cooperation","Global cooperation is essential to address climate change, as countries work towards emission reduction goals. International agreements, like the Paris Accord, set targets for reducing greenhouse gases. Despite differences in economic interests, cooperation is necessary to prevent catastrophic environmental impacts and protect future generations."},
                {"The Role of Virtual Reality in Education",  "Virtual reality is becoming an innovative tool in education, allowing students to experience immersive learning. VR helps with subjects like history, science, and geography by simulating real-world scenarios. As costs decrease, VR could become a standard tool in classrooms, making learning more engaging and accessible."},
                {"Food Security and Agricultural Technology", "Technological advances in agriculture are critical for food security. Precision farming, GM crops, and AI-driven analytics are helping farmers increase yield and efficiency. As climate change threatens crop yields, investing in sustainable agriculture technology is essential to ensure a stable food supply for the global population."},
                {"Rise of Telemedicine During the Pandemic","Telemedicine surged during the COVID-19 pandemic as healthcare providers sought safe ways to deliver care. Patients could access medical consultations remotely, reducing the risk of infection. Although in-person visits remain essential, telemedicine is expected to continue as an accessible option for routine healthcare."},
                {"Blockchain in Supply Chain Management",  "Blockchain technology is improving transparency and traceability in supply chain management. By recording each step in the chain, companies can reduce fraud and enhance accountability. This technology also helps with inventory management and regulatory compliance, benefiting sectors like food and pharmaceuticals that rely on strict monitoring."},
                {"Electric Planes: Future of Air Travel", "The development of electric planes promises a more sustainable future for air travel. Companies are investing in electric propulsion technologies to reduce carbon emissions and reliance on fossil fuels. While still in the early stages, electric planes could revolutionize short-haul flights, offering an eco-friendly alternative to traditional aviation."},
                {"AI and Automation in Customer Service", "Companies are increasingly using AI and automation to enhance customer service. Chatbots and virtual assistants handle routine queries, allowing human agents to focus on complex issues. While automation improves efficiency, businesses must balance it with a personal touch to ensure customer satisfaction and prevent service quality declines."},
                {"Privacy Concerns with Smart Home Devices",  "Smart home devices, from speakers to security cameras, offer convenience but raise privacy concerns. These devices collect data, often with limited transparency on how it's used. Consumers are urged to take precautions, such as changing default settings and understanding device privacy policies, to protect personal information."},
                {"Wearable Technology in Health Monitoring", "Wearable health tech, like fitness trackers and smartwatches, allows users to monitor their health in real-time. Devices can track heart rate, sleep patterns, and more, offering insights into personal health. The rise of wearables reflects a shift toward preventive healthcare, with potential benefits for early disease detection."},
                {"Carbon Capture: An Answer to Emissions?","Carbon capture technology is seen as a solution to reduce greenhouse gas emissions. It involves capturing carbon dioxide from the air and storing it underground. While promising, critics argue that it may not be enough to combat climate change without broader emission reductions across industries."},
                {"The Economics of Climate Change", "Climate change poses economic risks, from damaged infrastructure to disrupted agriculture. Economists warn that failure to address climate change could lead to substantial financial costs. Countries are urged to adopt sustainable practices and invest in resilience measures to protect their economies from climate-related disruptions."},
                {"Online Education and the Digital Divide",  "The rise of online education during the pandemic highlighted disparities in access to technology. Students in rural or low-income areas often lack reliable internet, creating a digital divide. Addressing this issue is essential to ensure equal educational opportunities and prevent widening achievement gaps."},
                {"Artificial Intelligence in Healthcare","Artificial Intelligence (AI) has emerged as a powerful tool in healthcare, assisting doctors with diagnosis, treatment recommendations, and patient monitoring. AI algorithms can analyze medical images, identify patterns, and predict outcomes, significantly improving efficiency and accuracy in patient care. While AI holds great potential, its widespread adoption in healthcare still faces challenges related to data privacy, ethics, and regulatory approval."},
                {"Automation in Manufacturing: A Game Changer","Automation is revolutionizing the manufacturing industry by improving production efficiency, reducing costs, and minimizing human errors. With the integration of robotics, AI, and machine learning, manufacturers are able to produce high-quality products at a faster rate. However, the shift toward automation raises concerns about job displacement and the need for workers to acquire new skills."},
                {"Impact of Artificial Intelligence on Employment", "AI's increasing role in the workplace has led to both excitement and concern. On the one hand, AI has the potential to create new jobs and improve productivity. On the other hand, there are fears that automation will lead to widespread job loss, particularly in industries that rely heavily on routine tasks. The future of work will require a balance between leveraging AI’s potential and ensuring economic stability for workers."},
                {"The Ethics of Autonomous Vehicles", "Autonomous vehicles (AVs) are changing the landscape of transportation, offering benefits such as improved safety, reduced traffic, and less environmental impact. However, ethical issues arise when it comes to decision-making in life-or-death situations. Who is responsible when an AV makes a controversial decision? As AV technology advances, it will be critical to develop ethical frameworks to guide their use on public roads."},
                {"Sustainable Fashion: The Future of the Industry", "Sustainable fashion is gaining popularity as consumers and brands alike recognize the environmental and ethical challenges posed by fast fashion. From eco-friendly materials to ethical labor practices, the industry is evolving to meet the demands of a more conscious consumer base. However, the transition to sustainability requires significant changes in production processes and consumer behavior."},
                {"The Role of Artificial Intelligence in Marketing","AI is transforming the marketing industry by enabling more personalized, efficient, and data-driven campaigns. Marketers are leveraging AI to analyze consumer behavior, optimize content delivery, and predict trends. AI-powered tools also assist in customer segmentation and targeted advertising. While AI can increase marketing effectiveness, it also raises concerns about privacy and data security."},
                {"Electric Vehicles: The Path to a Greener Future",  "Electric vehicles (EVs) are gaining traction as a sustainable alternative to gasoline-powered cars. EVs reduce carbon emissions, improve air quality, and decrease reliance on fossil fuels. However, challenges such as charging infrastructure, battery life, and manufacturing costs must be addressed to make EVs more accessible to the mass market. The shift toward electric transportation is a crucial step in combating climate change."},
                {"The Future of Augmented Reality in Retail", "Augmented Reality (AR) is transforming the retail experience by allowing customers to try on products virtually, visualize items in their homes, and make more informed purchasing decisions. Retailers are increasingly integrating AR into their stores and websites, creating immersive experiences that engage consumers in new ways. As AR technology advances, its impact on retail is expected to grow exponentially."},
                {"The Rise of Smart Cities","Smart cities are the next evolution of urban living, where technology and data are used to improve the quality of life for residents. From traffic management to energy efficiency, smart cities utilize sensors, data analytics, and IoT devices to optimize urban services and infrastructure. While smart cities offer numerous benefits, they also raise concerns about privacy, data security, and the digital divide."},
                {"The Role of Artificial Intelligence in Education", "Artificial Intelligence (AI) is increasingly being integrated into education to improve learning outcomes and personalize instruction. AI-powered tools can help educators identify student strengths and weaknesses, create tailored learning plans, and automate administrative tasks. However, the use of AI in education also raises ethical concerns about data privacy and the potential for bias in algorithms."},
        };


        String url = "jdbc:mysql://localhost:3306/news";
        String user = "root";
        String password = "Dulina@123";

        String insertSQL = "INSERT INTO article (title, content, category) VALUES (?, ?, ?)";

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            try (PreparedStatement statement = connection.prepareStatement(insertSQL)) {
                for (String[] article : articles) {
                    String title = article[0];
                    String content = article[1];

                    KeywordExtraction keywordExtraction = new KeywordExtraction();
                    String category = keywordExtraction.categorizeArticle(keywordExtraction.getTFvalue(article[1]));


                    statement.setString(1, title);
                    statement.setString(2, content);
                    statement.setString(3, category);

                    statement.executeUpdate();
                }

                System.out.println("Articles inserted successfully.");
            } catch (SQLException e) {
                System.out.println("Error while inserting data: " + e.getMessage());
            }
        } catch (SQLException e) {
            System.out.println("Connection failed: " + e.getMessage());
        }
    }


}